### ISSUE TITLE
Config gets overwritten on re-installation

### ISSUE THREAD

**Issue by tobox** [tuxd3v/ats#10]
I chose to go back to 0.2.0 from master, and followed the steps to install 0.2.0. 

The installation was successfull, but /etc/ats.conf was overwritten by the defaults.

IMHO, config files should not be overwritten without confirmation.

**Comment by tuxd3v** [comment]
Hello @tobox,
You right, that that is the normal behaviour, I will include a provision for that :)

Thanks for your Sugestion,
Best Regards
