### ISSUE TITLE
cannot disable service

### ISSUE THREAD

**Issue by dougcooper** [tuxd3v/ats#11]
```
root@rockpro64:/tmp/ats# systemctl disable ats
Failed to disable unit: No such file or directory
```

**Comment by tuxd3v** [comment]
Does you have it installed?

do a:
```lua
systemctl status ats;```

**Comment by dougcooper** [comment]
yes I installed it. `make install` worked fine and i could both stop and query the status of the service.

**Comment by tuxd3v** [comment]
if you install be hand,
Then to remove you need to remove by hand too :)

When using luarocks to install,
You only need to run( to uninstall ):
```lua
luarocks remove ats 
```

And it will be done for you automatically :)
is this issue related with the reported issue #12?

**Comment by dougcooper** [comment]
yes it is related. Your readme advises to use `make remove` and makes no mention of luarocks which must be the source of confusion.

**Comment by tuxd3v** [comment]
hello dougcooper,
My apologies, in fact its not very well explained..
I will update it.

Thank-you very much to point that.

Best Regards,
