### ISSUE TITLE
Porting ATS to SOPine Baseboard

### ISSUE THREAD

**Issue by curtyc** [tuxd3v/ats#13]
Hi tuxd3v

First of all, congratulations for the code. Very useful!

I am thinking to use that at a SOPine Baseboard (https://www.pine64.org/baseboard/), as follows:

> CPU0 Temperature:
/sys/class/thermal/thermal_zone0/temp
> GPU0 Temperature:
/sys/class/thermal/thermal_zone1/temp
> GPU1 Temperature:
/sys/class/thermal/thermal_zone2/temp

> PWM Control:
SOPine Baseboard PWM pin ---> Pi2 Header Pin 7 (A64 signal: S_PWM, pin: PL10) ---> gpio362

I have tried:

$ sudo vi /etc/ats.conf --->

---cut here---
--- Fan Cycling ON/OFF [ boolean ]
        ALWAYS_ON                       = false,

---  Assigning SysFs Locations for control..
        --
        -- CPU Thermal Zone[ String ]
        THERMAL0_CTL    = "/sys/class/thermal/thermal_zone0/temp",
        -- GPU Thermal Zone[ String ]
        THERMAL1_CTL    = "/sys/class/thermal/thermal_zone1/temp",
        -- FAN Control[ String ]
        --PWM_CTL         = "/sys/class/hwmon/hwmon0/pwm1",
        PWM_CTL= "/sys/class/gpio/gpio362/value",
---cut here---

and the service activates:

$ sudo systemctl status ats

* ats.service - ATS - Active Thermal Service
   Loaded: loaded (/lib/systemd/system/ats.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-10-16 22:43:34 UTC; 1min 5s ago
 Main PID: 1445 (lua)
    Tasks: 1 (limit: 2314)
   CGroup: /system.slice/ats.service
           `-1445 lua /usr/local/sbin/ats

but the behavior seems like ON-OFF and not driven by temperature...

Have I missed something?... :-/ 

Thanks in advance for any help.

PS: Fan can controlled to ON and OFF by CLI commands:
$ sudo cd /sys/class/gpio; echo 1 > gpio362/value
$ sudo cd /sys/class/gpio; echo 0 > gpio362/value

**Comment by tuxd3v** [comment]
Ola curtyc, :) 

If you stop the service and then run:
```lua
ats -t
```
What is the output( let it run for some 3 minutes.. )

After that,
In the configuration file '/etc/ats.conf', you have a option to stay Always ON,
try this config:
```lua
--- Fan Cycling ON/OFF [ boolean ]
        ALWAYS_ON          = true,
---  Assigning SysFs Locations for control..
        -- CPU Thermal Zone[ String ]
        THERMAL0_CTL    = "/sys/class/thermal/thermal_zone0/temp",
        -- GPU Thermal Zone[ String ]
        THERMAL1_CTL    = "/sys/class/thermal/thermal_zone1/temp",
        -- FAN Control[ String ]
        PWM_CTL= "/sys/class/gpio/gpio362/value",
```
then,
 ```lua
systemctl  stop ats; systemctl start ats
```
But it will give you values represented in a scale that has 2^8 values[ 0, 255 ]..
And you probably want only ON/OFF behaviour?

Accordingly with the [Linux-Sunxi Matrix](https://linux-sunxi.org/Linux_mainlining_effort#Status_Matrix), AllWinner A64 has pwm driver since Linux 4.19.

Cumprimentos,
tux

**Comment by tuxd3v** [comment]
Hi curtyc,
Something that I jst remember, I don't know if SOPine has hardware to drive a fan?
If it doesn't you need something like [this](https://github.com/tuxd3v/pwm_driver)..

You get pwm signal out of SOPine, and then use a hardware driver to drive it..

**Comment by curtyc** [comment]
Olá Tux3d

Thank you for this quick answer! :-)

I have changed /etc/ats.conf for:

---cut here---

        THERMAL0_CTL    = "/sys/class/thermal/thermal_zone0/temp",
        THERMAL1_CTL    = "/sys/class/thermal/thermal_zone1/temp",
        PWM_CTL         = "/sys/class/gpio/gpio362/value",

        MAX_CONTINUOUS_THERMAL_TEMP     = 60,
        MIN_CONTINUOUS_THERMAL_TEMP     = 40,

        MAX_PWM                         = 255,
        MIN_PWM                         = 20,

        ALWAYS_ON                       = true,

---cut here---

and runned:

$ sudo stress -v --cpu 8 --io 4 --vm 2 --vm-bytes 128M --timeout 120s

to heat the SoC, in parallel with:

$ sudo ats -t

for >3 minutes, as follows:

$ sudo /usr/local/sbin/ats -t

> info:'SYSTEM' Table
info:    'BOARD' Table
info:        'NAME' = SOPineBaseboard
info:        'CPU'  = A64
info:    'THERMAL0_CTL' = /sys/class/thermal/thermal_zone0/temp
info:    'THERMAL1_CTL' = /sys/class/thermal/thermal_zone1/temp
info:    'PWM_CTL'      = /sys/class/gpio/gpio362/value
info:    'MAX_CONTINUOUS_THERMAL_TEMP' = 60
info:    'MIN_CONTINUOUS_THERMAL_TEMP' = 40
info:    'MAX_PWM' = 255
info:    'MIN_PWM' = 20
info:    'ALWAYS_ON' = true
info:    'PROFILE_NAME' = profile0
info:    'PROFILE'      = 0
info:'Pratio' timers
info:    'Pratio[ -20 - 40 [' = 0
info:    'Pratio[ 40 ]'       = 20
info:    'Pratio[ 41 ]'       = 31
info:    'Pratio[ 42 ]'       = 43
info:    'Pratio[ 43 ]'       = 55
info:    'Pratio[ 44 ]'       = 67
info:    'Pratio[ 45 ]'       = 78
info:    'Pratio[ 46 ]'       = 90
info:    'Pratio[ 47 ]'       = 102
info:    'Pratio[ 48 ]'       = 114
info:    'Pratio[ 49 ]'       = 125
info:    'Pratio[ 50 ]'       = 137
info:    'Pratio[ 51 ]'       = 149
info:    'Pratio[ 52 ]'       = 161
info:    'Pratio[ 53 ]'       = 172
info:    'Pratio[ 54 ]'       = 184
info:    'Pratio[ 55 ]'       = 196
info:    'Pratio[ 56 ]'       = 208
info:    'Pratio[ 57 ]'       = 219
info:    'Pratio[ 58 ]'       = 231
info:    'Pratio[ 59 ]'       = 243
info:    'Pratio[ 60 ]'       = 255
info:    'Pratio[ 60 - 70 ['  = 255
--------------------
>Running for[ seconds ]................ 5
CPU Temperature[ max 70 °C ].......... 38
GPU Temperature[ max 70 °C ].......... 38
Fan PWM Duty Cycle value[ 0 - 255 ]... 0
--------------------
>Running for[ seconds ]................ 5
CPU Temperature[ max 70 °C ].......... 39
GPU Temperature[ max 70 °C ].......... 39
Fan PWM Duty Cycle value[ 0 - 255 ]... 0
--------------------
>Running for[ seconds ]................ 10
CPU Temperature[ max 70 °C ].......... 40
GPU Temperature[ max 70 °C ].......... 40
Fan PWM Duty Cycle value[ 0 - 255 ]... 20
--------------------
>Running for[ seconds ]................ 5
CPU Temperature[ max 70 °C ].......... 38
GPU Temperature[ max 70 °C ].......... 38
Fan PWM Duty Cycle value[ 0 - 255 ]... 0
--------------------
>Running for[ seconds ]................ 5
CPU Temperature[ max 70 °C ].......... 39
GPU Temperature[ max 70 °C ].......... 39
Fan PWM Duty Cycle value[ 0 - 255 ]... 0
--------------------
>Running for[ seconds ]................ 5
CPU Temperature[ max 70 °C ].......... 39
GPU Temperature[ max 70 °C ].......... 39
Fan PWM Duty Cycle value[ 0 - 255 ]... 0
--------------------
>Running for[ seconds ]................ 20
CPU Temperature[ max 70 °C ].......... 49
GPU Temperature[ max 70 °C ].......... 49
Fan PWM Duty Cycle value[ 0 - 255 ]... 125
--------------------
>Running for[ seconds ]................ 30
CPU Temperature[ max 70 °C ].......... 54
GPU Temperature[ max 70 °C ].......... 54
Fan PWM Duty Cycle value[ 0 - 255 ]... 184
--------------------
>Running for[ seconds ]................ 30
CPU Temperature[ max 70 °C ].......... 55
GPU Temperature[ max 70 °C ].......... 55
Fan PWM Duty Cycle value[ 0 - 255 ]... 196
--------------------
>Running for[ seconds ]................ 30
CPU Temperature[ max 70 °C ].......... 54
GPU Temperature[ max 70 °C ].......... 54
Fan PWM Duty Cycle value[ 0 - 255 ]... 184
--------------------
>Running for[ seconds ]................ 30
CPU Temperature[ max 70 °C ].......... 54
GPU Temperature[ max 70 °C ].......... 54
Fan PWM Duty Cycle value[ 0 - 255 ]... 184
--------------------
>Running for[ seconds ]................ 5
CPU Temperature[ max 70 °C ].......... 37
GPU Temperature[ max 70 °C ].......... 37
Fan PWM Duty Cycle value[ 0 - 255 ]... 0
--------------------
>Running for[ seconds ]................ 5
CPU Temperature[ max 70 °C ].......... 37
GPU Temperature[ max 70 °C ].......... 37
Fan PWM Duty Cycle value[ 0 - 255 ]... 0
--------------------
>Running for[ seconds ]................ 5
CPU Temperature[ max 70 °C ].......... 37
GPU Temperature[ max 70 °C ].......... 37
Fan PWM Duty Cycle value[ 0 - 255 ]... 0
--------------------
...

but the signal at SOPine Baseboard PWM pin (ie. Pi2 Header Pin 7), is only Off/Low (+0.138 V) or On/High (+1.777 V).

I understood that it is working correctly and the only thing be added is a PWM driver.
Is that correct my understanding?

Thanks in advance for your attention!

**Comment by curtyc** [comment]
> Hi curtyc,
> Something that I jst remember, I don't know if SOPine has hardware to drive a fan?
> If it doesn't you need something like [this](https://github.com/tuxd3v/pwm_driver)..
> 
> You get pwm signal out of SOPine, and then use a hardware driver to drive it..

I already have a similar circuit that is driving a small 5V Fan. 
Thanks :-)

**Comment by tuxd3v** [comment]
Yup it seems that you only need a small circuitry to drive the fan,
using the pwm signal from the board :)
