### ISSUE TITLE
Release 0.2.0 fails to parse arch 

### ISSUE THREAD

**Issue by Doty1154** [tuxd3v/ats#14]
I have a rockpro64,  running the latest Armbian bionic ubuntu build.
[Link to website](https://www.armbian.com/rockpro64)
[Link to download](https://dl.armbian.com/rockpro64/Ubuntu_bionic_default.7z)
 For some reason when i try to build the latest version gcc complains theres no argument for -march=
Perhaps Armbian  has a bad aarch output compared to the ayufan builds you've been using.
I was eventually able to compile the latest version by statically stating "armv8-a+crc" within the make file gcc commands rather then having it use $(Arch)
Heres the output from console using luarocks building process
```
root@rockpro64:~# luarocks build https://raw.githubusercontent.com/tuxd3v/ats/ma                                                                                                                                                             ster/ats-master-0.rockspec
Cloning into 'ats'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 24 (delta 1), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (24/24), 106.18 KiB | 1.66 MiB/s, done.
Resolving deltas: 100% (1/1), done.
Warning: variable CFLAGS was not passed in build_variables
** PLATFORM = linux  **
** OS       = 64Bits **
/usr/bin/env: 'lua': No such file or directory
** ARCH     =  **
/usr/bin/env: 'lua': No such file or directory
gcc -c -march= -fPIC -Wall -Werror -O3 -g -I/usr/include/lua5.3  -o debug.o src/                                                                                                                                                             debug.c
gcc: error: missing argument to '-march='
Makefile:191: recipe for target 'debug.o' failed
make: *** [debug.o] Error 1

Error: Build error: Failed building.
```

**Comment by tuxd3v** [comment]
Hello Doty1154,

You need to install the Dependencies first, see [this](https://github.com/tuxd3v/ats#1-install-dependencies). :)

**Comment by tuxd3v** [comment]
Hi,
You are trying the last release version?
try with the master branch, it is stable enough..
```lua
luarocks build https://raw.githubusercontent.com/tuxd3v/ats/master/ats-master-0.rockspec
```

**Comment by Doty1154** [comment]
i am a clown, i totally missed setting the lua environment variable thing. Thank you

**Comment by tuxd3v** [comment]
Hi Doty1154,
Everybody do mistakes, don't be so hard on you.
Sometimes we fail, the important thing is that you solved your problem. :)

Best Regards,
tux
