### ISSUE TITLE
PWM1 File keeps resetting to 0

### ISSUE THREAD

**Issue by JackGlobetrotter** [tuxd3v/ats#17]
Hey, it is still me,
i am running ATS on ubuntu Bionic with Kernel 5.3. Whenever i write something to the pwm1 file (/sys/class/hwmon/hwmon0/pwm1), and for that extend whenever the ats service writes to the file, it keeps resetting to 0 after some seconds. 
I stopped every service possibly accessing the pwm file without any changes. When i try to see what happens with inotifywait, there is nothing happening....
Here is what is happening:
https://www.icloud.com/iclouddrive/06Wsxaxx7aLoIiWQSt9x6V0Ug#Screen_Recording_2019-12-06_at_08.46
thanks again for  your help!

**Comment by tuxd3v** [comment]
hello,
Check if this service is installed:
```lua
~# dpkg -l|grep  fancontrol
```

if yes remove it.
```lua
fancontrol
```

**Comment by JackGlobetrotter** [comment]
Hello,
the service is not installed....the output is empty...

**Comment by tuxd3v** [comment]
> Hello,
> the service is not installed....the output is empty...
try using 'lsof' like this:
```lua
for i in {1..100000000..1}; do lsof -nP /sys/devices/platform/pwm-fan/hwmon/hwmon0/pwm1; done
``` 
let it run for a lot of time, and check when that file gets open..
If you won't find it, it could be that the driver has flows, and it misbehave.. it happened in the past, even with ayufan releases, last year..

**Comment by JackGlobetrotter** [comment]
the script closes after some seconds with the message "killed"

**Comment by tuxd3v** [comment]
that is a strange behaviour..
does you have some bogus thing in configuration, or something?

I never saw a case like that..
Since its working it continues working..

Maybe its a exceptional case?

**Comment by JackGlobetrotter** [comment]
Maybe...i am unable to find why....once the next armbian build is out i'm gonna switch...fan-pwm changes have been merged:)

**Comment by tuxd3v** [comment]
hello, I saw that in the Armbian '.config' file:
https://github.com/armbian/build/blob/master/config/kernel/linux-rockchip-current.config

Its already there but built as a module..
Maybe in the current version it his already there too..

And you only need to do a:
```lua
modprobe pwm-fan
```
Maybe it solves it :)

**Comment by JackGlobetrotter** [comment]
Will test later today:) thanks for your help:)

**Comment by JackGlobetrotter** [comment]
> Will test later today:) thanks for your help:)
> I am pretty sur the config is not in the last build (from 19/11, merge was done later), but maybe it can be done via updates

Not in the latest build nor updates yet

**Comment by JackGlobetrotter** [comment]
Latest Kernel 5.4.5 has needed config and the fan is working:)

**Comment by virtulis** [comment]
Did you ever figure out what was causing it? I'm seeing the same issue on Debian `6.1.0-41-arm64`. It's like there's some kind of a timer that just keeps resetting it to 0. Clearly not a fault of `ats` but not sure where else to even ask!

Edit: I ended up just commenting out this `if` https://github.com/tuxd3v/ats/blob/cab47b0636551a44ec38a752cdb096a192596d41/src/ats.c#L485 (and then found your PR with a similar "solution", lol)
