### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by dkebler** [tuxd3v/ats#2]
Building from source.  I did have old fanctl code loaded but manually removed the binary and service before finding this new version

```Install ATS Tool ..................: ats in /usr/sbin
Install ATS Service File ..........: ats.service in systemd
V0.1.6 or older detected, Removing it from System..
find: ‘/{lib/systemd/system,usr/{sbin,lib/aarch64-linux-gnu/lua/5.3}}’: No such file or directory
Makefile:43: recipe for target 'install' failed
```
There is no directory `/lua`  under `aarch64-linux-gnu`   

Makefile is looking for old stuff to erase and the directory doesn't exist
			find /{lib/systemd/system,usr/{sbin,lib/${TRIPLET}/lua/5.3}} -name fanctl -o -name sleep.so\* -o -name fanctl.service -exec rm -v {} \;	\

The if statement is uses ||  so it's finding some of those but not all so it drops in and then the error occurs.

**Comment by dkebler** [comment]
I just commented out the whole block and the install finished.  I'd suggest making those && or doing a separate if for each file to remove it individually.  Then if someone like make removes some of manually you'll only remove the remaining stuff.
```
		# if [ -L $(LDIR)/fanctl.so ] || [ -L $(LDIR)/sleep.so ] || [ -f $(LDIR)/fanctl.so.?.? ] || [ -f $(LDIR)/sleep.so.?.? ];then			\
		# 	echo "V0.1.6 or older detected, Removing it from System..";										\
		# 	systemctl stop fanctl 1> /dev/null 2>&1;												\
		# 	systemctl disable fanctl 1> /dev/null 2>&1;												\
		# 	journalctl -u fanctl --rotate 1> /dev/null 2>&1;											\
		# 	sync && sleep 1;															\
		# 	journalctl -u fanctl --vacuum-time=1s 	1> /dev/null 2>&1;										\
		# 	find /{lib/systemd/system,usr/{sbin,lib/${TRIPLET}/lua/5.3}} -name fanctl -o -name sleep.so\* -o -name fanctl.service -exec rm -v {} \;	\
		# ;fi	
```

**Comment by tuxd3v** [comment]
Also, I hade forget to update the luarocks config file, tu automatically assign triplet, its now done!
