### ISSUE TITLE
fan not spinning ayufan new kernel release 

### ISSUE THREAD

**Issue by pine-clover** [tuxd3v/ats#20]
i am running buster minimal and the fan isn't running with ats.

had no problem installing. fan turns on with manjaro arm so i know it works.

Linux rockpro64 5.6.0-1137-ayufan-ge57f05e7bf8f #ayufan SMP Wed Apr 15 10:16:02 UTC 2020 aarch64 GNU/Linux

**Comment by pine-clover** [comment]
fixed.

**Comment by tuxd3v** [comment]
hello pine-clover,
can you describe what the issue were?

best regards,
tux

**Comment by ljishen** [comment]
I'm having the same issue as @alexr4535 on the same rockpro64 release. The installation process goes well without any errors. The ats service is running:

➜  ~ sudo service ats status                                                                      
● ats.service - ATS - Active Thermal Service
     Loaded: loaded (/usr/local/lib/luarocks/rocks/ats/master-0/ats.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2020-10-27 18:06:11 PDT; 7min ago
   Main PID: 110769 (lua)
      Tasks: 1 (limit: 4448)
     Memory: 392.0K
     CGroup: /system.slice/ats.service
             └─110769 lua /usr/local/sbin/ats

Oct 27 18:06:11 rockpro64 systemd[1]: Started ATS - Active Thermal Service.

But the `ats --test` does not activate the fan.
