### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by d6e** [tuxd3v/ats#22]
What's this project licensed as?

**Comment by d6e** [comment]
Sorry, I've been trying to write a nix package for this, but I need to know it's license...

**Comment by tuxd3v** [comment]
hello d6e,
A package would be nice :)
The license that I started is in 'docs/License'.

I just used that "small license" at least to have some Licensing.. it is minimalist..
But its a very reduced License( maybe I will change it to GPLv2, if it suits better your needs.. ).

What packages do you would like to create?

Thanks in Advance,
Best Regards
tux

**Comment by d6e** [comment]
> The license that I started is in 'docs/License'.
Ahhh I didn't think of looking there.

> What packages do you would like to create?
I tried to package it as a [Nix](https://nixos.org/) service, but gave up after packaging Lua and C got pretty complicated. Instead, I sort of wrote my [own fan controller](https://github.com/d6e/fanboi) in Rust using a PID controller library so I'll probably be abandoning that effort. Sorry.
