### ISSUE TITLE
Fans always run at full speed

### ISSUE THREAD

**Issue by nicolasbadia** [tuxd3v/ats#25]
I have purchased this https://pine64.com/product/rockpro64-metal-desktop-nas-casing and connected the fan on `+FAN-`.
Because the fan was always running at full speed, I've installed ats (with the command `luarocks build https://raw.githubusercontent.com/tuxd3v/ats/master/ats-master-0.rockspec`) on my rockpro64 (`Linux rockpro64 5.9.14-rockchip64 #20.11.4 SMP PREEMPT Tue Dec 15 08:52:20 CET 2020 aarch64 aarch64 aarch64 GNU/Linux`) but, even if the current CPU temp is 35°C, the fan still run at full speed. I believe the fan should have stopped. I did not change the ats default configuration.
ats service is `active (running)`.
Any idea on with it is not working as expected?

**Comment by chippey5** [comment]
@nicolasbadia I had to add more paths for the fan control on my 2 rockpro64 NAS. Try using [this config](https://github.com/chippey5/ats/blob/master/etc/ats.conf) in your ats.conf instead. I also created a small Python script that waits for these files to be created, but I don't know if this is needed anymore. Let me know if you're still having the issue.

**Comment by chippey5** [comment]
[#26](https://github.com/tuxd3v/ats/pull/26/files)

**Comment by nicolasbadia** [comment]
Awesome, as soon as I added `/sys/devices/platform/pwm-fan/hwmon/hwmon3/pwm1` and restarted ats, it started working.

**Comment by chippey5** [comment]
Nice, just beware that I've seen all of these paths used with my rockpro64's:

```
PWM_CTL         = {
                        "/sys/class/hwmon/hwmon0/pwm1",
                        "/sys/devices/platform/pwm-fan/hwmon/hwmon0/pwm1",
                        "/sys/devices/platform/pwm-fan/hwmon/hwmon1/pwm1",
                        "/sys/devices/platform/pwm-fan/hwmon/hwmon2/pwm1",
                        "/sys/devices/platform/pwm-fan/hwmon/hwmon3/pwm1"
},
```

**Comment by nicolasbadia** [comment]
Ok, good to know. Thanks.
