### ISSUE TITLE
Service installs but ats won't start.

### ISSUE THREAD

**Issue by ootoovak** [tuxd3v/ats#4]
First of all thanks for writing and sharing this project. 😃Seems like it will be very useful to have. I'm currently having a issue with my install though.

I've tried both the command with `luarocks` as well as using Git to clone the repo and build with `make` and `make install`.

`make install` fails with:

```bash
Install ATS Tool ..................: ats in /usr/local/sbin
Install ATS Service File ..........: ats.service in systemd
Remove previous ATS Library .......: ats.so.* from /usr/local/lib/lua/5.3
Install new ATS Library ...........: ats.so.0.2 in /usr/local/lib/lua/5.3
Create soname symLink .............: ats.so in /usr/local/lib/lua/5.3
Starting ATS Service..
● ats.service - ATS - Active Thermal Service
   Loaded: loaded (/lib/systemd/system/ats.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-11-07 23:38:04 UTC; 1s ago
  Process: 4154 ExecStart=/usr/local/sbin/ats (code=exited, status=1/FAILURE)
 Main PID: 4154 (code=exited, status=1/FAILURE)
Makefile:45: recipe for target 'install' failed
make: *** [install] Error 3
```

And checking with `sudo /usr/local/sbin/ats --test` returns:

```bash
getConditions: Warning, Values { THERMAL0_CTL, THERMAL1_CTL, FAN_CTL }: /sys/class/thermal/thermal_zone0/temp, /sys/class/thermal/thermal_zone1/temp, ERROR
exit 1
```

Am I missing something?

Note: I'm using the RockPro64 with NAS case (including heatsink and fan).

**Comment by tuxd3v** [comment]
Hello ootoovak,
You welcome :)

I see, the last part of the error, is very important:

"getConditions: Warning, Values { THERMAL0_CTL, THERMAL1_CTL, FAN_CTL }: /sys/class/thermal/thermal_zone0/temp, /sys/class/thermal/thermal_zone1/temp, ERROR"

It is a pré-check, for detecting PWM capabilities, and sensor reading for temperatures..
Your kernel needs to be updated..

Do the Following:
`sudo apt-get update
apt-get install linux-firmware-image-4.4.138-1097-rockchip-ayufan-gb5128c0a1684
apt-get install linux-headers-4.4.138-1097-rockchip-ayufan-gb5128c0a1684
apt-get install linux-image-4.4.138-1097-rockchip-ayufan-gb5128c0a1684
sudo reboot`

Then try to install with Luarocks by option 1.
It should now work :)

Can you confirm?

**Comment by tuxd3v** [comment]
Ok, nice you succeed!
There are 2 profiles, one for 10mm taller fans and another for 20 mm taller fans( less power given that the fan is more powerfull already ).

By default, it comes with the configuration for 10mm taller fan.
If you notice that, it is too much aggressive with speed noise, or something, you can change to profile 2.

For that, edit file /usr/local/sbin/ats
```sh
in line 67:
"	FANSPEC				= "profile1""
Change "profile1" to "profile2"
save file and:
service ats restart
service ats status
```
and its done :)

Best Regards,

**Comment by ootoovak** [comment]
That is very good to know, thank you. I'm using the one for the NAS box casing from the Pine64 store. https://www.pine64.org/?product=fan-for-rockpro64-metal-desktopnas-casing
