### ISSUE TITLE
I get error on make install

### ISSUE THREAD

**Issue by grimace** [tuxd3v/ats#5]
● ats.service - ATS - Active Thermal Service
   Loaded: loaded (/lib/systemd/system/ats.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2018-12-27 18:03:45 UTC; 1s ago
  Process: 23494 ExecStart=/usr/local/sbin/ats (code=exited, status=1/FAILURE)
 Main PID: 23494 (code=exited, status=1/FAILURE)

Dec 27 18:03:45 rockpro64 systemd[1]: ats.service: Main process exited, code=exited, status=1/FAILURE
Dec 27 18:03:45 rockpro64 systemd[1]: ats.service: Failed with result 'exit-code'.
Makefile:102: recipe for target 'install' failed
make: *** [install] Error 3

**Comment by tuxd3v** [comment]
Hello grimace,

can you please run ATs in test mode:
`/usr/local/sbin/ats -t`
or
`/usr/local/sbin/ats --test`

What is the output of it?
Regards

**Comment by tuxd3v** [comment]
you need to install at least kernel version 4.4.138-1094..

Do this:
`apt-get install linux-image-4.4.138-1097-rockchip-ayufan-gb5128c0a1684 linux-headers-4.4.138-1097-rockchip-ayufan-gb5128c0a1684 linux-firmware-image-4.4.138-1097-rockchip-ayufan-gb5128c0a1684
reboot`
You should see fan starting at boot..

If you want you can then run also in test mode :)

**Comment by grimace** [comment]
Looks like that did the trick:

`sudo /usr/local/sbin/ats -t
[sudo] password for otto: 
info:'SYSTEM' Table
info:    'BOARD' Table
info:        'NAME' = ROCKPRO64
info:        'CPU'  = RK3399
info:    'THERMAL0_CTL' = /sys/class/thermal/thermal_zone0/temp
info:    'THERMAL1_CTL' = /sys/class/thermal/thermal_zone1/temp
info:    'PWM_CTL'      = /sys/class/hwmon/hwmon0/pwm1
info:    'MAX_CONTINUOUS_THERMAL_TEMP' = 60
info:    'MIN_CONTINUOUS_THERMAL_TEMP' = 40
info:    'MAX_PWM' = 255
info:    'MIN_PWM' = 40
info:    'ALWAYS_ON' = false
info:    'PROFILE_NAME' = profile0
info:    'PROFILE'      = 0
info:'Pratio' timers
info:    'Pratio[ -20 - 40 [' = 0
info:    'Pratio[ 40 ]'       = 40
info:    'Pratio[ 41 ]'       = 50
info:    'Pratio[ 42 ]'       = 61
info:    'Pratio[ 43 ]'       = 72
info:    'Pratio[ 44 ]'       = 83
info:    'Pratio[ 45 ]'       = 93
info:    'Pratio[ 46 ]'       = 104
info:    'Pratio[ 47 ]'       = 115
info:    'Pratio[ 48 ]'       = 126
info:    'Pratio[ 49 ]'       = 136
info:    'Pratio[ 50 ]'       = 147
info:    'Pratio[ 51 ]'       = 158
info:    'Pratio[ 52 ]'       = 169
info:    'Pratio[ 53 ]'       = 179
info:    'Pratio[ 54 ]'       = 190
info:    'Pratio[ 55 ]'       = 201
info:    'Pratio[ 56 ]'       = 212
info:    'Pratio[ 57 ]'       = 222
info:    'Pratio[ 58 ]'       = 233
info:    'Pratio[ 59 ]'       = 244
info:    'Pratio[ 60 ]'       = 255
info:    'Pratio[ 60 - 70 ['  = 255
Stop ATS Service first [ service ats stop ]..
`
