### ISSUE TITLE
Compatible with Rock64?

### ISSUE THREAD

**Issue by martinschm** [tuxd3v/ats#9]
Hi,
Do you know if it will work with the little brother Rock64 (not Pro)?

Best
Martin

**Comment by tuxd3v** [comment]
Hello @martinschm,
At software Level, It will work for sure.
But at the moment ATS only works in boards that have a Fan connector.. that is the problem..

In the future, 
I am planning to develop a driver for boards that doesn't have a PWM Fan connector..
It will be assigned to GPIO, taking the 5v, and the Ground pins..
So it will need 3 pins( 2 for power connection, and 1 for fan control ), and will be a very tiny board connected there, but I have yet to develop it..
